[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_volanaka = "Dyzh44sBUJYppZctNY1fbi25YL39PSiekUVqJYtc6jgc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "app/private-keys/eqima.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
